name: Action Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo ${{ github.token }}
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: List files
        run: |
          pwd
          ls -a

      - name: Hello World Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Log time
        run: echo "${{ steps.greet.output.time }}"
        

