name: eks-cluster-onboarding
on: 
  push:
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened
jobs:
  argocd_cli_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Install ArgoCD_CLI
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.0.0
          command: version
          options: --client
      - name: shell command
        run: |
          argocd version --client

      
       

