name: eks-cluster-onboarding
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
      - assigned
      - opened
      - reopened
env:
  argocd_username: admin
  argocd_endpoint: a6c5005195b864da5acf161ce1b231f7-1000891572.us-east-1.elb.amazonaws.com 
    
jobs:
  argocd_cli_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Install ArgoCD_CLI
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.0.0
          command: version
          options: --client
          
      - name: shell command
        run: |
          argocd login ${argocd_endpoint} --username ${argocd_username} --password ${{secrets.ARGOCD_PASSWORD}} --insecure 
          argocd version
          argocd cluster list -o json


      - name: Get AWS credentials from Vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: https://vault-dev0-na10001.io.coupadev.com
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            aws/creds/ciop-pipeline access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/ciop-pipeline secret_key | AWS_SECRET_ACCESS_KEY ;
            aws/creds/ciop-pipeline security_token | AWS_SESSION_TOKEN ;


      
       

