name: eks-cluster-onboarding
on: 
  push:
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened
jobs:
  argocd_cli_install:
    runs-on: ubuntu-latest
    steps:
      - name: Install ArgoCD apiVersion
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.0.0
          command: version
          options: --client
      

